export enum ChangeType {
  LOAD_BOARD,
  UPDATE_BOARD,
  UPDATE_BOARD_AFTER_BACKLOG_TOGGLE,
  APPLY_FILTERS,
  CHANGE_SWIMLANE,
  CHANGE_COLUMN_VISIBILITY,
  SWITCH_VIEW_MODE,
  TOGGLE_SWIMLANE_SHOW_EMPTY,
  UPDATE_ISSUE_DETAIL,
  INIT_HELP_TEXTS,
  TOGGLE_SWIMLANE_COLLAPSED,
  UPDATE_SEARCH,
  TOGGLE_HIDE_SEARCH_NON_MATCHES
}
